// console.log(2>=1);
// console.log(2<1);
// console.log(2>=1);
// console.log(2<=1);
// console.log(2==1);
// console.log(2!=1);
console.log("2">1);
console.log("02">1);
console.log(null>0);
console.log(null==0);
console.log(null>=0);
console.log(undefined==0);
console.log(undefined>0);
console.log(undefined<0);

//NOTE: Dont compare Such type of values(Undefined and Null) with other types.

console.log("2"===2);




